---
title: Yan Ting Yuen
timezone: UTC
collections:
  news:
    title: New
    output: true
    permalink: "/:title/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  work:
    title: other work
    output: true
    permalink: "/:title/"
defaults:
- scope:
    path: ''
    type: work
  values:
    author: Yan Ting
    layout: work-title
    title: ''
    upload-image: ''
    image-description: ''
    vimeo: ''
    copyright_country_year: Yan Ting Yuen (2017), Netherlands
- scope:
    path: ''
    type: news
  values:
    layout: news
    title: ''
    title-chinese: 
    upload-image: ''
    image-description: ''
    author: Yan Ting
    excerpt: ''
email: yantingyuen (at) gmail.com
description: 
baseurl: 
mobile: 10
url: https://yantingyuennl.github.io/
twitter_username: yantingyuen
imdb_url: http://www.imdb.com/name/nm1211089/
copyright: 2017 Yan Ting Yuen
copyright_chinese: 袁欣婷
bg-image: "/img/bg_alt.svg"
favicon-png-image: "/uploads/favicon.png"
markdown: kramdown
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
- node_modules
- gulpfile.js
